-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.Account where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified FatLoginResponse.AccountType
import qualified FatLoginResponse.AggErrorInfo

data Account = Account
  { accountId :: !(PB.Maybe PB.Text)
  , accountName :: !(PB.Maybe PB.Text)
  , accountType :: !(PB.Maybe FatLoginResponse.AccountType.AccountType)
  , activating :: !(PB.Maybe PB.Bool)
  , active :: !(PB.Maybe PB.Bool)
  , aggErrorInfo :: !(PB.Maybe FatLoginResponse.AggErrorInfo.AggErrorInfo)
  , autosaveAccountPriority :: !(PB.Maybe PB.Int64)
  , balance :: !(PB.Maybe PB.Int64)
  , bankNeedsPin :: !(PB.Maybe PB.Bool)
  , canBeAutosaveFundingSource :: !(PB.Maybe PB.Bool)
  , canBeAutosaveTarget :: !(PB.Maybe PB.Bool)
  , doesNotSupportPending :: !(PB.Maybe PB.Bool)
  , institutionId :: !(PB.Maybe PB.Int64)
  , institutionLoginId :: !(PB.Maybe PB.Text)
  , institutionName :: !(PB.Maybe PB.Text)
  , isAutosaveSource :: !(PB.Maybe PB.Bool)
  , isAutosaveTarget :: !(PB.Maybe PB.Bool)
  , lastDigits :: !(PB.Maybe PB.Text)
  , needsMfa :: !(PB.Maybe PB.Bool)
  , needsReauth :: !(PB.Maybe PB.Bool)
  , noReauthBefore :: !(PB.Maybe PB.Int64)
  , onboardingFinished :: !(PB.Maybe PB.Bool)
  , onboardingStarted :: !(PB.Maybe PB.Bool)
  , softDelinked :: !(PB.Maybe PB.Bool)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default Account where
  defaultVal = Account
    { accountId = PB.defaultVal
    , accountName = PB.defaultVal
    , accountType = PB.defaultVal
    , activating = PB.defaultVal
    , active = PB.defaultVal
    , aggErrorInfo = PB.defaultVal
    , autosaveAccountPriority = PB.defaultVal
    , balance = PB.defaultVal
    , bankNeedsPin = PB.defaultVal
    , canBeAutosaveFundingSource = PB.defaultVal
    , canBeAutosaveTarget = PB.defaultVal
    , doesNotSupportPending = PB.defaultVal
    , institutionId = PB.defaultVal
    , institutionLoginId = PB.defaultVal
    , institutionName = PB.defaultVal
    , isAutosaveSource = PB.defaultVal
    , isAutosaveTarget = PB.defaultVal
    , lastDigits = PB.defaultVal
    , needsMfa = PB.defaultVal
    , needsReauth = PB.defaultVal
    , noReauthBefore = PB.defaultVal
    , onboardingFinished = PB.defaultVal
    , onboardingStarted = PB.defaultVal
    , softDelinked = PB.defaultVal
    }

instance PB.Mergeable Account where
  merge a b = Account
    { accountId = PB.merge (accountId a) (accountId b)
    , accountName = PB.merge (accountName a) (accountName b)
    , accountType = PB.merge (accountType a) (accountType b)
    , activating = PB.merge (activating a) (activating b)
    , active = PB.merge (active a) (active b)
    , aggErrorInfo = PB.merge (aggErrorInfo a) (aggErrorInfo b)
    , autosaveAccountPriority = PB.merge (autosaveAccountPriority a) (autosaveAccountPriority b)
    , balance = PB.merge (balance a) (balance b)
    , bankNeedsPin = PB.merge (bankNeedsPin a) (bankNeedsPin b)
    , canBeAutosaveFundingSource = PB.merge (canBeAutosaveFundingSource a) (canBeAutosaveFundingSource b)
    , canBeAutosaveTarget = PB.merge (canBeAutosaveTarget a) (canBeAutosaveTarget b)
    , doesNotSupportPending = PB.merge (doesNotSupportPending a) (doesNotSupportPending b)
    , institutionId = PB.merge (institutionId a) (institutionId b)
    , institutionLoginId = PB.merge (institutionLoginId a) (institutionLoginId b)
    , institutionName = PB.merge (institutionName a) (institutionName b)
    , isAutosaveSource = PB.merge (isAutosaveSource a) (isAutosaveSource b)
    , isAutosaveTarget = PB.merge (isAutosaveTarget a) (isAutosaveTarget b)
    , lastDigits = PB.merge (lastDigits a) (lastDigits b)
    , needsMfa = PB.merge (needsMfa a) (needsMfa b)
    , needsReauth = PB.merge (needsReauth a) (needsReauth b)
    , noReauthBefore = PB.merge (noReauthBefore a) (noReauthBefore b)
    , onboardingFinished = PB.merge (onboardingFinished a) (onboardingFinished b)
    , onboardingStarted = PB.merge (onboardingStarted a) (onboardingStarted b)
    , softDelinked = PB.merge (softDelinked a) (softDelinked b)
    }

instance PB.Required Account where
  reqTags _ = PB.fromList []

instance PB.WireMessage Account where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{accountId = PB.merge (accountId self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 5 PB.LenDelim) self = (\v -> self{accountName = PB.merge (accountName self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 7 PB.LenDelim) self = (\v -> self{accountType = PB.merge (accountType self) v}) <$> PB.getEnumOpt
  fieldToValue (PB.WireTag 15 PB.VarInt) self = (\v -> self{activating = PB.merge (activating self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 4 PB.VarInt) self = (\v -> self{active = PB.merge (active self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 20 PB.LenDelim) self = (\v -> self{aggErrorInfo = PB.merge (aggErrorInfo self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 25 PB.VarInt) self = (\v -> self{autosaveAccountPriority = PB.merge (autosaveAccountPriority self) v}) <$> PB.getInt64Opt
  fieldToValue (PB.WireTag 6 PB.VarInt) self = (\v -> self{balance = PB.merge (balance self) v}) <$> PB.getInt64Opt
  fieldToValue (PB.WireTag 17 PB.VarInt) self = (\v -> self{bankNeedsPin = PB.merge (bankNeedsPin self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 24 PB.VarInt) self = (\v -> self{canBeAutosaveFundingSource = PB.merge (canBeAutosaveFundingSource self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 23 PB.VarInt) self = (\v -> self{canBeAutosaveTarget = PB.merge (canBeAutosaveTarget self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 18 PB.VarInt) self = (\v -> self{doesNotSupportPending = PB.merge (doesNotSupportPending self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 2 PB.VarInt) self = (\v -> self{institutionId = PB.merge (institutionId self) v}) <$> PB.getInt64Opt
  fieldToValue (PB.WireTag 19 PB.LenDelim) self = (\v -> self{institutionLoginId = PB.merge (institutionLoginId self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 3 PB.LenDelim) self = (\v -> self{institutionName = PB.merge (institutionName self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 21 PB.VarInt) self = (\v -> self{isAutosaveSource = PB.merge (isAutosaveSource self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 22 PB.VarInt) self = (\v -> self{isAutosaveTarget = PB.merge (isAutosaveTarget self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 8 PB.LenDelim) self = (\v -> self{lastDigits = PB.merge (lastDigits self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 9 PB.VarInt) self = (\v -> self{needsMfa = PB.merge (needsMfa self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 10 PB.VarInt) self = (\v -> self{needsReauth = PB.merge (needsReauth self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 11 PB.VarInt) self = (\v -> self{noReauthBefore = PB.merge (noReauthBefore self) v}) <$> PB.getInt64Opt
  fieldToValue (PB.WireTag 14 PB.VarInt) self = (\v -> self{onboardingFinished = PB.merge (onboardingFinished self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 13 PB.VarInt) self = (\v -> self{onboardingStarted = PB.merge (onboardingStarted self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 16 PB.VarInt) self = (\v -> self{softDelinked = PB.merge (softDelinked self) v}) <$> PB.getBoolOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringOpt (PB.WireTag 1 PB.LenDelim) (accountId self)
    PB.putStringOpt (PB.WireTag 5 PB.LenDelim) (accountName self)
    PB.putEnumOpt (PB.WireTag 7 PB.LenDelim) (accountType self)
    PB.putBoolOpt (PB.WireTag 15 PB.VarInt) (activating self)
    PB.putBoolOpt (PB.WireTag 4 PB.VarInt) (active self)
    PB.putMessageOpt (PB.WireTag 20 PB.LenDelim) (aggErrorInfo self)
    PB.putInt64Opt (PB.WireTag 25 PB.VarInt) (autosaveAccountPriority self)
    PB.putInt64Opt (PB.WireTag 6 PB.VarInt) (balance self)
    PB.putBoolOpt (PB.WireTag 17 PB.VarInt) (bankNeedsPin self)
    PB.putBoolOpt (PB.WireTag 24 PB.VarInt) (canBeAutosaveFundingSource self)
    PB.putBoolOpt (PB.WireTag 23 PB.VarInt) (canBeAutosaveTarget self)
    PB.putBoolOpt (PB.WireTag 18 PB.VarInt) (doesNotSupportPending self)
    PB.putInt64Opt (PB.WireTag 2 PB.VarInt) (institutionId self)
    PB.putStringOpt (PB.WireTag 19 PB.LenDelim) (institutionLoginId self)
    PB.putStringOpt (PB.WireTag 3 PB.LenDelim) (institutionName self)
    PB.putBoolOpt (PB.WireTag 21 PB.VarInt) (isAutosaveSource self)
    PB.putBoolOpt (PB.WireTag 22 PB.VarInt) (isAutosaveTarget self)
    PB.putStringOpt (PB.WireTag 8 PB.LenDelim) (lastDigits self)
    PB.putBoolOpt (PB.WireTag 9 PB.VarInt) (needsMfa self)
    PB.putBoolOpt (PB.WireTag 10 PB.VarInt) (needsReauth self)
    PB.putInt64Opt (PB.WireTag 11 PB.VarInt) (noReauthBefore self)
    PB.putBoolOpt (PB.WireTag 14 PB.VarInt) (onboardingFinished self)
    PB.putBoolOpt (PB.WireTag 13 PB.VarInt) (onboardingStarted self)
    PB.putBoolOpt (PB.WireTag 16 PB.VarInt) (softDelinked self)


