-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.AccountType where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data AccountType = Unrecognized | Asset | CreditCard
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default AccountType where
  defaultVal = Unrecognized

instance PB.Mergeable AccountType where

instance PB.WireEnum AccountType where
  intToEnum 0 = Unrecognized
  intToEnum 1 = Asset
  intToEnum 2 = CreditCard
  intToEnum _ = PB.defaultVal

  enumToInt Unrecognized = 0
  enumToInt Asset = 1
  enumToInt CreditCard = 2


