-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.AggErrorInfo where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified FatLoginResponse.AggErrorStatus

data AggErrorInfo = AggErrorInfo
  { accountStatusDescription :: !(PB.Maybe PB.Text)
  , errorStatus :: !(PB.Maybe FatLoginResponse.AggErrorStatus.AggErrorStatus)
  , statusStartTimestamp :: !(PB.Maybe PB.Int64)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default AggErrorInfo where
  defaultVal = AggErrorInfo
    { accountStatusDescription = PB.defaultVal
    , errorStatus = PB.defaultVal
    , statusStartTimestamp = PB.defaultVal
    }

instance PB.Mergeable AggErrorInfo where
  merge a b = AggErrorInfo
    { accountStatusDescription = PB.merge (accountStatusDescription a) (accountStatusDescription b)
    , errorStatus = PB.merge (errorStatus a) (errorStatus b)
    , statusStartTimestamp = PB.merge (statusStartTimestamp a) (statusStartTimestamp b)
    }

instance PB.Required AggErrorInfo where
  reqTags _ = PB.fromList []

instance PB.WireMessage AggErrorInfo where
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{accountStatusDescription = PB.merge (accountStatusDescription self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{errorStatus = PB.merge (errorStatus self) v}) <$> PB.getEnumOpt
  fieldToValue (PB.WireTag 3 PB.VarInt) self = (\v -> self{statusStartTimestamp = PB.merge (statusStartTimestamp self) v}) <$> PB.getInt64Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringOpt (PB.WireTag 2 PB.LenDelim) (accountStatusDescription self)
    PB.putEnumOpt (PB.WireTag 1 PB.LenDelim) (errorStatus self)
    PB.putInt64Opt (PB.WireTag 3 PB.VarInt) (statusStartTimestamp self)


