-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.AutosaveData where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified FatLoginResponse.AutosaveStatus
import qualified FatLoginResponse.ScheduledTransfer
import qualified FatLoginResponse.ScheduledTransfer
import qualified FatLoginResponse.ScheduledTransfer

data AutosaveData = AutosaveData
  { autosaveStatus :: !(PB.Maybe FatLoginResponse.AutosaveStatus.AutosaveStatus)
  , fundingAccountId :: !(PB.Maybe PB.Text)
  , hasMinimumFundingAccountBalance :: !(PB.Maybe PB.Bool)
  , hasSavingsTargetAmount :: !(PB.Maybe PB.Bool)
  , minimumFundingAccountBalance :: !(PB.Maybe PB.Int64)
  , pastScheduledTransfers :: !(PB.Seq FatLoginResponse.ScheduledTransfer.ScheduledTransfer)
  , savingsTargetAmount :: !(PB.Maybe PB.Int64)
  , scheduledSmansfer :: !(PB.Maybe FatLoginResponse.ScheduledTransfer.ScheduledTransfer)
  , scheduledWithdrawal :: !(PB.Maybe FatLoginResponse.ScheduledTransfer.ScheduledTransfer)
  , targetAccountId :: !(PB.Maybe PB.Text)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default AutosaveData where
  defaultVal = AutosaveData
    { autosaveStatus = PB.defaultVal
    , fundingAccountId = PB.defaultVal
    , hasMinimumFundingAccountBalance = PB.defaultVal
    , hasSavingsTargetAmount = PB.defaultVal
    , minimumFundingAccountBalance = PB.defaultVal
    , pastScheduledTransfers = PB.defaultVal
    , savingsTargetAmount = PB.defaultVal
    , scheduledSmansfer = PB.defaultVal
    , scheduledWithdrawal = PB.defaultVal
    , targetAccountId = PB.defaultVal
    }

instance PB.Mergeable AutosaveData where
  merge a b = AutosaveData
    { autosaveStatus = PB.merge (autosaveStatus a) (autosaveStatus b)
    , fundingAccountId = PB.merge (fundingAccountId a) (fundingAccountId b)
    , hasMinimumFundingAccountBalance = PB.merge (hasMinimumFundingAccountBalance a) (hasMinimumFundingAccountBalance b)
    , hasSavingsTargetAmount = PB.merge (hasSavingsTargetAmount a) (hasSavingsTargetAmount b)
    , minimumFundingAccountBalance = PB.merge (minimumFundingAccountBalance a) (minimumFundingAccountBalance b)
    , pastScheduledTransfers = PB.merge (pastScheduledTransfers a) (pastScheduledTransfers b)
    , savingsTargetAmount = PB.merge (savingsTargetAmount a) (savingsTargetAmount b)
    , scheduledSmansfer = PB.merge (scheduledSmansfer a) (scheduledSmansfer b)
    , scheduledWithdrawal = PB.merge (scheduledWithdrawal a) (scheduledWithdrawal b)
    , targetAccountId = PB.merge (targetAccountId a) (targetAccountId b)
    }

instance PB.Required AutosaveData where
  reqTags _ = PB.fromList []

instance PB.WireMessage AutosaveData where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{autosaveStatus = PB.merge (autosaveStatus self) v}) <$> PB.getEnumOpt
  fieldToValue (PB.WireTag 6 PB.LenDelim) self = (\v -> self{fundingAccountId = PB.merge (fundingAccountId self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 4 PB.VarInt) self = (\v -> self{hasMinimumFundingAccountBalance = PB.merge (hasMinimumFundingAccountBalance self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 2 PB.VarInt) self = (\v -> self{hasSavingsTargetAmount = PB.merge (hasSavingsTargetAmount self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 5 PB.VarInt) self = (\v -> self{minimumFundingAccountBalance = PB.merge (minimumFundingAccountBalance self) v}) <$> PB.getInt64Opt
  fieldToValue (PB.WireTag 10 PB.LenDelim) self = (\v -> self{pastScheduledTransfers = PB.append (pastScheduledTransfers self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 3 PB.VarInt) self = (\v -> self{savingsTargetAmount = PB.merge (savingsTargetAmount self) v}) <$> PB.getInt64Opt
  fieldToValue (PB.WireTag 8 PB.LenDelim) self = (\v -> self{scheduledSmansfer = PB.merge (scheduledSmansfer self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 9 PB.LenDelim) self = (\v -> self{scheduledWithdrawal = PB.merge (scheduledWithdrawal self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 7 PB.LenDelim) self = (\v -> self{targetAccountId = PB.merge (targetAccountId self) v}) <$> PB.getStringOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putEnumOpt (PB.WireTag 1 PB.LenDelim) (autosaveStatus self)
    PB.putStringOpt (PB.WireTag 6 PB.LenDelim) (fundingAccountId self)
    PB.putBoolOpt (PB.WireTag 4 PB.VarInt) (hasMinimumFundingAccountBalance self)
    PB.putBoolOpt (PB.WireTag 2 PB.VarInt) (hasSavingsTargetAmount self)
    PB.putInt64Opt (PB.WireTag 5 PB.VarInt) (minimumFundingAccountBalance self)
    PB.putMessageList (PB.WireTag 10 PB.LenDelim) (pastScheduledTransfers self)
    PB.putInt64Opt (PB.WireTag 3 PB.VarInt) (savingsTargetAmount self)
    PB.putMessageOpt (PB.WireTag 8 PB.LenDelim) (scheduledSmansfer self)
    PB.putMessageOpt (PB.WireTag 9 PB.LenDelim) (scheduledWithdrawal self)
    PB.putStringOpt (PB.WireTag 7 PB.LenDelim) (targetAccountId self)


