-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.AutosaveStatus where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data AutosaveStatus = NotSetUp | Active | Paused
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default AutosaveStatus where
  defaultVal = NotSetUp

instance PB.Mergeable AutosaveStatus where

instance PB.WireEnum AutosaveStatus where
  intToEnum 0 = NotSetUp
  intToEnum 1 = Active
  intToEnum 2 = Paused
  intToEnum _ = PB.defaultVal

  enumToInt NotSetUp = 0
  enumToInt Active = 1
  enumToInt Paused = 2


