-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.BucketedTransactionsCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

data BucketedTransactionsCard = BucketedTransactionsCard
  { bucketIds :: !(PB.Seq PB.Text)
  , transactionIds :: !(PB.Seq PB.Text)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default BucketedTransactionsCard where
  defaultVal = BucketedTransactionsCard
    { bucketIds = PB.defaultVal
    , transactionIds = PB.defaultVal
    }

instance PB.Mergeable BucketedTransactionsCard where
  merge a b = BucketedTransactionsCard
    { bucketIds = PB.merge (bucketIds a) (bucketIds b)
    , transactionIds = PB.merge (transactionIds a) (transactionIds b)
    }

instance PB.Required BucketedTransactionsCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage BucketedTransactionsCard where
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{bucketIds = PB.append (bucketIds self) v}) <$> PB.getString
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{transactionIds = PB.append (transactionIds self) v}) <$> PB.getString
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringList (PB.WireTag 2 PB.LenDelim) (bucketIds self)
    PB.putStringList (PB.WireTag 1 PB.LenDelim) (transactionIds self)


