-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.BucketType where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data BucketType = LegacyInsight | Bill | MagicDontCount | DebitInsight | CreditInsight | RecurringIncome | MagicTransfer | MagicSavings
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default BucketType where
  defaultVal = LegacyInsight

instance PB.Mergeable BucketType where

instance PB.WireEnum BucketType where
  intToEnum 0 = LegacyInsight
  intToEnum 1 = Bill
  intToEnum 3 = MagicDontCount
  intToEnum 5 = DebitInsight
  intToEnum 6 = CreditInsight
  intToEnum 7 = RecurringIncome
  intToEnum 8 = MagicTransfer
  intToEnum 9 = MagicSavings
  intToEnum _ = PB.defaultVal

  enumToInt LegacyInsight = 0
  enumToInt Bill = 1
  enumToInt MagicDontCount = 3
  enumToInt DebitInsight = 5
  enumToInt CreditInsight = 6
  enumToInt RecurringIncome = 7
  enumToInt MagicTransfer = 8
  enumToInt MagicSavings = 9


