-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.CacheContents where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified FatLoginResponse.Account
import qualified FatLoginResponse.AutosaveData
import qualified FatLoginResponse.Bucket
import qualified FatLoginResponse.Card
import qualified FatLoginResponse.FeatureFlags
import qualified FatLoginResponse.Transaction
import qualified FatLoginResponse.Transaction

data CacheContents = CacheContents
  { accounts :: !(PB.Seq FatLoginResponse.Account.Account)
  , autosaveData :: !(PB.Maybe FatLoginResponse.AutosaveData.AutosaveData)
  , buckets :: !(PB.Seq FatLoginResponse.Bucket.Bucket)
  , cards :: !(PB.Seq FatLoginResponse.Card.Card)
  , features :: !(PB.Maybe FatLoginResponse.FeatureFlags.FeatureFlags)
  , hasV3Spendable :: !(PB.Maybe PB.Bool)
  , projectedTransactions :: !(PB.Seq FatLoginResponse.Transaction.Transaction)
  , transactions :: !(PB.Seq FatLoginResponse.Transaction.Transaction)
  , transactionsCursor :: !(PB.Maybe PB.Int64)
  , v3Spendable :: !(PB.Maybe PB.Int64)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default CacheContents where
  defaultVal = CacheContents
    { accounts = PB.defaultVal
    , autosaveData = PB.defaultVal
    , buckets = PB.defaultVal
    , cards = PB.defaultVal
    , features = PB.defaultVal
    , hasV3Spendable = PB.defaultVal
    , projectedTransactions = PB.defaultVal
    , transactions = PB.defaultVal
    , transactionsCursor = PB.defaultVal
    , v3Spendable = PB.defaultVal
    }

instance PB.Mergeable CacheContents where
  merge a b = CacheContents
    { accounts = PB.merge (accounts a) (accounts b)
    , autosaveData = PB.merge (autosaveData a) (autosaveData b)
    , buckets = PB.merge (buckets a) (buckets b)
    , cards = PB.merge (cards a) (cards b)
    , features = PB.merge (features a) (features b)
    , hasV3Spendable = PB.merge (hasV3Spendable a) (hasV3Spendable b)
    , projectedTransactions = PB.merge (projectedTransactions a) (projectedTransactions b)
    , transactions = PB.merge (transactions a) (transactions b)
    , transactionsCursor = PB.merge (transactionsCursor a) (transactionsCursor b)
    , v3Spendable = PB.merge (v3Spendable a) (v3Spendable b)
    }

instance PB.Required CacheContents where
  reqTags _ = PB.fromList []

instance PB.WireMessage CacheContents where
  fieldToValue (PB.WireTag 20 PB.LenDelim) self = (\v -> self{accounts = PB.append (accounts self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 50 PB.LenDelim) self = (\v -> self{autosaveData = PB.merge (autosaveData self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 22 PB.LenDelim) self = (\v -> self{buckets = PB.append (buckets self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 30 PB.LenDelim) self = (\v -> self{cards = PB.append (cards self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 40 PB.LenDelim) self = (\v -> self{features = PB.merge (features self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 32 PB.VarInt) self = (\v -> self{hasV3Spendable = PB.merge (hasV3Spendable self) v}) <$> PB.getBoolOpt
  fieldToValue (PB.WireTag 23 PB.LenDelim) self = (\v -> self{projectedTransactions = PB.append (projectedTransactions self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 21 PB.LenDelim) self = (\v -> self{transactions = PB.append (transactions self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 24 PB.VarInt) self = (\v -> self{transactionsCursor = PB.merge (transactionsCursor self) v}) <$> PB.getInt64Opt
  fieldToValue (PB.WireTag 31 PB.VarInt) self = (\v -> self{v3Spendable = PB.merge (v3Spendable self) v}) <$> PB.getInt64Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putMessageList (PB.WireTag 20 PB.LenDelim) (accounts self)
    PB.putMessageOpt (PB.WireTag 50 PB.LenDelim) (autosaveData self)
    PB.putMessageList (PB.WireTag 22 PB.LenDelim) (buckets self)
    PB.putMessageList (PB.WireTag 30 PB.LenDelim) (cards self)
    PB.putMessageOpt (PB.WireTag 40 PB.LenDelim) (features self)
    PB.putBoolOpt (PB.WireTag 32 PB.VarInt) (hasV3Spendable self)
    PB.putMessageList (PB.WireTag 23 PB.LenDelim) (projectedTransactions self)
    PB.putMessageList (PB.WireTag 21 PB.LenDelim) (transactions self)
    PB.putInt64Opt (PB.WireTag 24 PB.VarInt) (transactionsCursor self)
    PB.putInt64Opt (PB.WireTag 31 PB.VarInt) (v3Spendable self)


