-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.CancelledScheduledTransferCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype CancelledScheduledTransferCard = CancelledScheduledTransferCard
  { scheduledTransferId :: PB.Maybe PB.Text
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default CancelledScheduledTransferCard where
  defaultVal = CancelledScheduledTransferCard
    { scheduledTransferId = PB.defaultVal
    }

instance PB.Mergeable CancelledScheduledTransferCard where
  merge a b = CancelledScheduledTransferCard
    { scheduledTransferId = PB.merge (scheduledTransferId a) (scheduledTransferId b)
    }

instance PB.Required CancelledScheduledTransferCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage CancelledScheduledTransferCard where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{scheduledTransferId = PB.merge (scheduledTransferId self) v}) <$> PB.getStringOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringOpt (PB.WireTag 1 PB.LenDelim) (scheduledTransferId self)


