-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.CardType where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data CardType = Normies | Transfer | BucketedTransactions | SuggestedTransaction | Explainer | AdjustSpendable | GenericText | SuggestedAddToExistingBucket | Display | Summary | UpcomingSmansfer | PendingSmansfer | CancelledSmansfer | ClearedSmansfer
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default CardType where
  defaultVal = Normies

instance PB.Mergeable CardType where

instance PB.WireEnum CardType where
  intToEnum 1 = Normies
  intToEnum 2 = Transfer
  intToEnum 3 = BucketedTransactions
  intToEnum 4 = SuggestedTransaction
  intToEnum 7 = AdjustSpendable
  intToEnum 8 = GenericText
  intToEnum 9 = SuggestedAddToExistingBucket
  intToEnum 10 = Display
  intToEnum 11 = Summary
  intToEnum 12 = UpcomingSmansfer
  intToEnum 13 = PendingSmansfer
  intToEnum 14 = CancelledSmansfer
  intToEnum 15 = ClearedSmansfer
  intToEnum _ = PB.defaultVal

  enumToInt Normies = 1
  enumToInt Transfer = 2
  enumToInt BucketedTransactions = 3
  enumToInt SuggestedTransaction = 4
  enumToInt Explainer = 4
  enumToInt AdjustSpendable = 7
  enumToInt GenericText = 8
  enumToInt SuggestedAddToExistingBucket = 9
  enumToInt Display = 10
  enumToInt Summary = 11
  enumToInt UpcomingSmansfer = 12
  enumToInt PendingSmansfer = 13
  enumToInt CancelledSmansfer = 14
  enumToInt ClearedSmansfer = 15


