-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.CardFlag where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data CardFlag = Dismissed
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default CardFlag where
  defaultVal = Dismissed

instance PB.Mergeable CardFlag where

instance PB.WireEnum CardFlag where
  intToEnum 1 = Dismissed
  intToEnum _ = PB.defaultVal

  enumToInt Dismissed = 1


