-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.ClearedScheduledTransferCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

data ClearedScheduledTransferCard = ClearedScheduledTransferCard
  { scheduledTransferId :: !(PB.Maybe PB.Text)
  , sourceTransactionId :: !(PB.Maybe PB.Text)
  , targetTransactionId :: !(PB.Maybe PB.Text)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ClearedScheduledTransferCard where
  defaultVal = ClearedScheduledTransferCard
    { scheduledTransferId = PB.defaultVal
    , sourceTransactionId = PB.defaultVal
    , targetTransactionId = PB.defaultVal
    }

instance PB.Mergeable ClearedScheduledTransferCard where
  merge a b = ClearedScheduledTransferCard
    { scheduledTransferId = PB.merge (scheduledTransferId a) (scheduledTransferId b)
    , sourceTransactionId = PB.merge (sourceTransactionId a) (sourceTransactionId b)
    , targetTransactionId = PB.merge (targetTransactionId a) (targetTransactionId b)
    }

instance PB.Required ClearedScheduledTransferCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage ClearedScheduledTransferCard where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{scheduledTransferId = PB.merge (scheduledTransferId self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{sourceTransactionId = PB.merge (sourceTransactionId self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 3 PB.LenDelim) self = (\v -> self{targetTransactionId = PB.merge (targetTransactionId self) v}) <$> PB.getStringOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringOpt (PB.WireTag 1 PB.LenDelim) (scheduledTransferId self)
    PB.putStringOpt (PB.WireTag 2 PB.LenDelim) (sourceTransactionId self)
    PB.putStringOpt (PB.WireTag 3 PB.LenDelim) (targetTransactionId self)


