-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.DisplayType where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data DisplayType = NewMonth
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default DisplayType where
  defaultVal = NewMonth

instance PB.Mergeable DisplayType where

instance PB.WireEnum DisplayType where
  intToEnum 1 = NewMonth
  intToEnum _ = PB.defaultVal

  enumToInt NewMonth = 1


