-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.DisplayCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified FatLoginResponse.DisplayType

data DisplayCard = DisplayCard
  { description :: !(PB.Maybe PB.Text)
  , displayType :: !(PB.Maybe FatLoginResponse.DisplayType.DisplayType)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default DisplayCard where
  defaultVal = DisplayCard
    { description = PB.defaultVal
    , displayType = PB.defaultVal
    }

instance PB.Mergeable DisplayCard where
  merge a b = DisplayCard
    { description = PB.merge (description a) (description b)
    , displayType = PB.merge (displayType a) (displayType b)
    }

instance PB.Required DisplayCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage DisplayCard where
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{description = PB.merge (description self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{displayType = PB.merge (displayType self) v}) <$> PB.getEnumOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringOpt (PB.WireTag 2 PB.LenDelim) (description self)
    PB.putEnumOpt (PB.WireTag 1 PB.LenDelim) (displayType self)


