-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.DisplayStyle where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data DisplayStyle = MonthToMonth | AllTime
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default DisplayStyle where
  defaultVal = MonthToMonth

instance PB.Mergeable DisplayStyle where

instance PB.WireEnum DisplayStyle where
  intToEnum 1 = MonthToMonth
  intToEnum 2 = AllTime
  intToEnum _ = PB.defaultVal

  enumToInt MonthToMonth = 1
  enumToInt AllTime = 2


