-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.ExplainerType where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data ExplainerType = Welcome | RenameAccounts | DontCount | Icons | Trackers | EnableAutosave
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ExplainerType where
  defaultVal = Welcome

instance PB.Mergeable ExplainerType where

instance PB.WireEnum ExplainerType where
  intToEnum 1 = Welcome
  intToEnum 2 = RenameAccounts
  intToEnum 4 = DontCount
  intToEnum 5 = Icons
  intToEnum 6 = Trackers
  intToEnum 7 = EnableAutosave
  intToEnum _ = PB.defaultVal

  enumToInt Welcome = 1
  enumToInt RenameAccounts = 2
  enumToInt DontCount = 4
  enumToInt Icons = 5
  enumToInt Trackers = 6
  enumToInt EnableAutosave = 7


