-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.ExplainerCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified FatLoginResponse.ExplainerType

newtype ExplainerCard = ExplainerCard
  { explainerType :: PB.Maybe FatLoginResponse.ExplainerType.ExplainerType
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ExplainerCard where
  defaultVal = ExplainerCard
    { explainerType = PB.defaultVal
    }

instance PB.Mergeable ExplainerCard where
  merge a b = ExplainerCard
    { explainerType = PB.merge (explainerType a) (explainerType b)
    }

instance PB.Required ExplainerCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage ExplainerCard where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{explainerType = PB.merge (explainerType self) v}) <$> PB.getEnumOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putEnumOpt (PB.WireTag 1 PB.LenDelim) (explainerType self)


