-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.FatLoginError where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data FatLoginError = NoError | SomeError | NoDemoAccounts
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default FatLoginError where
  defaultVal = NoError

instance PB.Mergeable FatLoginError where

instance PB.WireEnum FatLoginError where
  intToEnum 0 = NoError
  intToEnum 1 = SomeError
  intToEnum 2 = NoDemoAccounts
  intToEnum _ = PB.defaultVal

  enumToInt NoError = 0
  enumToInt SomeError = 1
  enumToInt NoDemoAccounts = 2


