-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.GenericTextCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

data GenericTextCard = GenericTextCard
  { callToActionText :: !(PB.Maybe PB.Text)
  , callToActionUrl :: !(PB.Maybe PB.Text)
  , copy :: !(PB.Maybe PB.Text)
  , header :: !(PB.Maybe PB.Text)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default GenericTextCard where
  defaultVal = GenericTextCard
    { callToActionText = PB.defaultVal
    , callToActionUrl = PB.defaultVal
    , copy = PB.defaultVal
    , header = PB.defaultVal
    }

instance PB.Mergeable GenericTextCard where
  merge a b = GenericTextCard
    { callToActionText = PB.merge (callToActionText a) (callToActionText b)
    , callToActionUrl = PB.merge (callToActionUrl a) (callToActionUrl b)
    , copy = PB.merge (copy a) (copy b)
    , header = PB.merge (header a) (header b)
    }

instance PB.Required GenericTextCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage GenericTextCard where
  fieldToValue (PB.WireTag 3 PB.LenDelim) self = (\v -> self{callToActionText = PB.merge (callToActionText self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 4 PB.LenDelim) self = (\v -> self{callToActionUrl = PB.merge (callToActionUrl self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{copy = PB.merge (copy self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{header = PB.merge (header self) v}) <$> PB.getStringOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringOpt (PB.WireTag 3 PB.LenDelim) (callToActionText self)
    PB.putStringOpt (PB.WireTag 4 PB.LenDelim) (callToActionUrl self)
    PB.putStringOpt (PB.WireTag 2 PB.LenDelim) (copy self)
    PB.putStringOpt (PB.WireTag 1 PB.LenDelim) (header self)


