-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.NormieCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype NormieCard = NormieCard
  { transactionIds :: PB.Seq PB.Text
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default NormieCard where
  defaultVal = NormieCard
    { transactionIds = PB.defaultVal
    }

instance PB.Mergeable NormieCard where
  merge a b = NormieCard
    { transactionIds = PB.merge (transactionIds a) (transactionIds b)
    }

instance PB.Required NormieCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage NormieCard where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{transactionIds = PB.append (transactionIds self) v}) <$> PB.getString
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringList (PB.WireTag 1 PB.LenDelim) (transactionIds self)


