-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.PendingScheduledTransferCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype PendingScheduledTransferCard = PendingScheduledTransferCard
  { scheduledTransferId :: PB.Maybe PB.Text
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default PendingScheduledTransferCard where
  defaultVal = PendingScheduledTransferCard
    { scheduledTransferId = PB.defaultVal
    }

instance PB.Mergeable PendingScheduledTransferCard where
  merge a b = PendingScheduledTransferCard
    { scheduledTransferId = PB.merge (scheduledTransferId a) (scheduledTransferId b)
    }

instance PB.Required PendingScheduledTransferCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage PendingScheduledTransferCard where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{scheduledTransferId = PB.merge (scheduledTransferId self) v}) <$> PB.getStringOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringOpt (PB.WireTag 1 PB.LenDelim) (scheduledTransferId self)


