-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.SuggestedTransactionCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified FatLoginResponse.Bucket

data SuggestedTransactionCard = SuggestedTransactionCard
  { bucket :: !(PB.Maybe FatLoginResponse.Bucket.Bucket)
  , transactionId :: !(PB.Maybe PB.Text)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SuggestedTransactionCard where
  defaultVal = SuggestedTransactionCard
    { bucket = PB.defaultVal
    , transactionId = PB.defaultVal
    }

instance PB.Mergeable SuggestedTransactionCard where
  merge a b = SuggestedTransactionCard
    { bucket = PB.merge (bucket a) (bucket b)
    , transactionId = PB.merge (transactionId a) (transactionId b)
    }

instance PB.Required SuggestedTransactionCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage SuggestedTransactionCard where
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{bucket = PB.merge (bucket self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{transactionId = PB.merge (transactionId self) v}) <$> PB.getStringOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putMessageOpt (PB.WireTag 2 PB.LenDelim) (bucket self)
    PB.putStringOpt (PB.WireTag 1 PB.LenDelim) (transactionId self)


