-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.SuggestedAddToExistingBucketCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

data SuggestedAddToExistingBucketCard = SuggestedAddToExistingBucketCard
  { bucketId :: !(PB.Maybe PB.Text)
  , transactionId :: !(PB.Maybe PB.Text)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SuggestedAddToExistingBucketCard where
  defaultVal = SuggestedAddToExistingBucketCard
    { bucketId = PB.defaultVal
    , transactionId = PB.defaultVal
    }

instance PB.Mergeable SuggestedAddToExistingBucketCard where
  merge a b = SuggestedAddToExistingBucketCard
    { bucketId = PB.merge (bucketId a) (bucketId b)
    , transactionId = PB.merge (transactionId a) (transactionId b)
    }

instance PB.Required SuggestedAddToExistingBucketCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage SuggestedAddToExistingBucketCard where
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{bucketId = PB.merge (bucketId self) v}) <$> PB.getStringOpt
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{transactionId = PB.merge (transactionId self) v}) <$> PB.getStringOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringOpt (PB.WireTag 2 PB.LenDelim) (bucketId self)
    PB.putStringOpt (PB.WireTag 1 PB.LenDelim) (transactionId self)


