-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.SummaryCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

data SummaryCard = SummaryCard
  { activeBucketIds :: !(PB.Seq PB.Text)
  , highlightedTransactionIds :: !(PB.Seq PB.Text)
  , totalBills :: !(PB.Maybe PB.Int64)
  , totalSpending :: !(PB.Maybe PB.Int64)
  , totalTransactions :: !(PB.Maybe PB.Int64)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SummaryCard where
  defaultVal = SummaryCard
    { activeBucketIds = PB.defaultVal
    , highlightedTransactionIds = PB.defaultVal
    , totalBills = PB.defaultVal
    , totalSpending = PB.defaultVal
    , totalTransactions = PB.defaultVal
    }

instance PB.Mergeable SummaryCard where
  merge a b = SummaryCard
    { activeBucketIds = PB.merge (activeBucketIds a) (activeBucketIds b)
    , highlightedTransactionIds = PB.merge (highlightedTransactionIds a) (highlightedTransactionIds b)
    , totalBills = PB.merge (totalBills a) (totalBills b)
    , totalSpending = PB.merge (totalSpending a) (totalSpending b)
    , totalTransactions = PB.merge (totalTransactions a) (totalTransactions b)
    }

instance PB.Required SummaryCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage SummaryCard where
  fieldToValue (PB.WireTag 4 PB.LenDelim) self = (\v -> self{activeBucketIds = PB.append (activeBucketIds self) v}) <$> PB.getString
  fieldToValue (PB.WireTag 5 PB.LenDelim) self = (\v -> self{highlightedTransactionIds = PB.append (highlightedTransactionIds self) v}) <$> PB.getString
  fieldToValue (PB.WireTag 2 PB.VarInt) self = (\v -> self{totalBills = PB.merge (totalBills self) v}) <$> PB.getInt64Opt
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{totalSpending = PB.merge (totalSpending self) v}) <$> PB.getInt64Opt
  fieldToValue (PB.WireTag 3 PB.VarInt) self = (\v -> self{totalTransactions = PB.merge (totalTransactions self) v}) <$> PB.getInt64Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringList (PB.WireTag 4 PB.LenDelim) (activeBucketIds self)
    PB.putStringList (PB.WireTag 5 PB.LenDelim) (highlightedTransactionIds self)
    PB.putInt64Opt (PB.WireTag 2 PB.VarInt) (totalBills self)
    PB.putInt64Opt (PB.WireTag 1 PB.VarInt) (totalSpending self)
    PB.putInt64Opt (PB.WireTag 3 PB.VarInt) (totalTransactions self)


