-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.TransferCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype TransferCard = TransferCard
  { transactionIds :: PB.Seq PB.Text
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default TransferCard where
  defaultVal = TransferCard
    { transactionIds = PB.defaultVal
    }

instance PB.Mergeable TransferCard where
  merge a b = TransferCard
    { transactionIds = PB.merge (transactionIds a) (transactionIds b)
    }

instance PB.Required TransferCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage TransferCard where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{transactionIds = PB.append (transactionIds self) v}) <$> PB.getString
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringList (PB.WireTag 1 PB.LenDelim) (transactionIds self)


