-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.UpcomingScheduledTransferCard where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype UpcomingScheduledTransferCard = UpcomingScheduledTransferCard
  { scheduledTransferId :: PB.Maybe PB.Text
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default UpcomingScheduledTransferCard where
  defaultVal = UpcomingScheduledTransferCard
    { scheduledTransferId = PB.defaultVal
    }

instance PB.Mergeable UpcomingScheduledTransferCard where
  merge a b = UpcomingScheduledTransferCard
    { scheduledTransferId = PB.merge (scheduledTransferId a) (scheduledTransferId b)
    }

instance PB.Required UpcomingScheduledTransferCard where
  reqTags _ = PB.fromList []

instance PB.WireMessage UpcomingScheduledTransferCard where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{scheduledTransferId = PB.merge (scheduledTransferId self) v}) <$> PB.getStringOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putStringOpt (PB.WireTag 1 PB.LenDelim) (scheduledTransferId self)


