-- Generated by protobuf-simple. DO NOT EDIT!
module FatLoginResponse.UserAgent where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data UserAgent = Unspecified | Iphone | Android | Web | Console | GoogleGlass | AndroidWear | Iwatch | Skynet | Toaster | Blackberry | WindowsPhone
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default UserAgent where
  defaultVal = Unspecified

instance PB.Mergeable UserAgent where

instance PB.WireEnum UserAgent where
  intToEnum 1 = Unspecified
  intToEnum 2 = Iphone
  intToEnum 3 = Android
  intToEnum 4 = Web
  intToEnum 5 = Console
  intToEnum 6 = GoogleGlass
  intToEnum 7 = AndroidWear
  intToEnum 8 = Iwatch
  intToEnum 9 = Skynet
  intToEnum 10 = Toaster
  intToEnum 11 = Blackberry
  intToEnum 12 = WindowsPhone
  intToEnum _ = PB.defaultVal

  enumToInt Unspecified = 1
  enumToInt Iphone = 2
  enumToInt Android = 3
  enumToInt Web = 4
  enumToInt Console = 5
  enumToInt GoogleGlass = 6
  enumToInt AndroidWear = 7
  enumToInt Iwatch = 8
  enumToInt Skynet = 9
  enumToInt Toaster = 10
  enumToInt Blackberry = 11
  enumToInt WindowsPhone = 12


